version: '3'
services:
   qtrend-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: qtrend-dashboard-container
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:ro
    